I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 846, in script
    ALEXANDRA "What? I’m here to look for you. I’m Alexandra, and I’m the one in charge of the tour. I understand that you got a little lost, but we need to get back to the tour. I’ve got a meeting after this with leadership and I’m not really sure how they’d react if I was late to my first meeting as president."
Exception: Sayer 'MOGAN' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 846, in script
    ALEXANDRA "What? I’m here to look for you. I’m Alexandra, and I’m the one in charge of the tour. I understand that you got a little lost, but we need to get back to the tour. I’ve got a meeting after this with leadership and I’m not really sure how they’d react if I was late to my first meeting as president."
  File "C:\Users\Joshua\Desktop\IMPORTANT SCREENSHOTS\New folder\renpy-6.99.12.4-sdk\renpy\ast.py", line 593, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Joshua\Desktop\IMPORTANT SCREENSHOTS\New folder\renpy-6.99.12.4-sdk\renpy\ast.py", line 509, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'MOGAN' is not defined.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Full Course 1.0
